services:
  gitstreamy:
    image: nginx
    ports:
        - 8501:80
    volumes:
        - /gitstreamy:/usr/share/nginx/html
  healthcheck:
    test: curl --fail http://localhost || exit 1
    interval: 60s
    retries: 5
    start_period: 20s
    timeout: 10s
