version: "3.8"

services:
  assemblit:
    image: thomaseleff/assemblit:v0.1.0
    container_name: assemblit
    ports:
      - 8501:8501
    environment:

      # Web-app configuration settings
      NAME: assemblit
      HOME_PAGE_NAME: Home

      # Authentication settings
      REQUIRE_AUTHENTICATION: true

      # Users db settings
      USERS_DB_NAME: users
      USERS_DB_QUERY_INDEX: user_id

      # Sessions db settings
      SESSIONS_DB_NAME: studies
      SESSIONS_DB_QUERY_INDEX: study_id

      # Data db settings
      DATA_DB_NAME: data
      DATA_DB_QUERY_INDEX: dataset_id

    healthcheck:
      test: curl --fail http://localhost:8501 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
